import { NSP_EMPLOYEE } from 'app/consts';

export const KEY_REDUCER_SAGA = `${NSP_EMPLOYEE}reducerProjects`;

export const EMPLOYEE_CALL = `${NSP_EMPLOYEE}_EMPLOYEE_CALL`;
export const EMPLOYEE_CALL_FAILED = `${NSP_EMPLOYEE}_EMPLOYEE_CALL_FAILED`;
export const EMPLOYEE_CALL_SUCCESS = `${NSP_EMPLOYEE}_EMPLOYEE_CALL_SUCCESS`;
